[env:pico]
platform = raspberrypi
board = pico
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
monitor_port = COM4

; pio device list => USB Port suchen


lib_deps =
    https://github.com/RudolphRiedel/FT800-FT813/archive/refs/heads/5.x.zip



build_flags =
    ; Display: Riverdi RVT50 / 800x480
    -D EVE_RVT50
 

    ; EVE control pins
    -D EVE_CS=17
    -D EVE_PDN=20

    ; SPI0 on RP2040 Pico
    ; ACHTUNG PINS können unter Core nicht verlegt werden.
    -D EVE_SCK=18
    -D EVE_MOSI=19
    -D EVE_MISO=16

    ; Display orientation
    -D EVE_ROTATE=0
